name: "New Github actions repo by ${{ github.actor }}"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Відображення змінної середовища GITHUB_ACTIONS"
        run: 'echo "Змінна середовища GITHUB_ACTIONS: $GITHUB_ACTIONS"'

      - name: "Показати назву гілки та репозиторію"
        run: |
          echo "Подія: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Назва гілки (для PR): ${{ github.head_ref }}"
          else
            echo "Назва гілки (для push): ${{ github.ref }}"
          fi
          echo "Назва репозиторію: ${{ github.repository }}"

      - name: "Відображення події, що ініціювала запуск робочого процесу"
        run: 'echo "Подія, що ініціювала цей робочий процес: ${{ github.event_name }}"'

      - name: "Показати всі контекстні змінні GitHub"
        # Використовуйте багаторядковий літерал з 'cat' та 'EOF' для безпечного виводу JSON
        run: |
          echo "Повний контекст GitHub:"
          cat <<EOF_GITHUB_CONTEXT
          ${{ toJSON(github) }}
          EOF_GITHUB_CONTEXT
