name: "Робочий процес ${{ github.actor }} для PR та push"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Відображення змінної середовища GITHUB_ACTIONS"
        run: 'echo "Змінна середовища GITHUB_ACTIONS: $GITHUB_ACTIONS"'

      - name: "Показати назву гілки та репозиторію"
        run: 'echo "Назва гілки: ${{ github.ref }}"; echo "Назва репозиторію: ${{ github.repository }}"'

      - name: "Відображення події, що ініціювала запуск робочого процесу"
        run: 'echo "Подія, що ініціювала цей робочий процес: ${{ github.event_name }}"'

      - name: "Показати всі контекстні змінні GitHub"
        run: 'echo "${{ toJson(github) }}"'
